repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff wrapper
        entry: uv run ruff check --force-exclude
        language: system
        types: [python]
        require_serial: true
      - id: ruff-format
        name: ruff format wrapper
        entry: uv run ruff format --force-exclude
        language: system
        types: [python]
        require_serial: true
      - id: pyright
        name: pyright wrapper
        entry: uv run pyright
        language: system
        types: [python]
        pass_filenames: false
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2 # Use the latest stable version
    hooks:
      - id: gitleaks
